# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: myos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: dnf
    repos:
      copr:
        - atim/starship
        - solopasha/hyprland
        - ublue-os/staging
        - kylegospo/bazzite-multilib
        - kylegospo/bazzite
        - peterwu/rendezvous
        - yuezk/globalprotect-openconnect
        - yalter/niri
        - ryanabx/cosmic-epoch
        - wiiznokes/cosmic-applets-unofficial
        - sneexy/zen-browser
      files:
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
    install:  
      skip-unavailable: true  # Whether to continue with the install if packages are unavailable
      packages:
        # Editors and Terminal Tools
        - starship
        - helix
        - kitty
        - emacs
        
        # System Tools
        - timeshift
        - gnome-boxes
        - kdeconnectd
        - antimicrox
        - cliphist
        
        # Document Viewers
        - zathura
        - zathura-pdf-mupdf
        - zathura-ps
        - zathura-djvu
        
        # Development Libraries
        - openssl-devel
        - libgda
        - libgda-sqlite
        - zlib-devel
        - libjpeg-turbo-devel
        - python3-devel
        - libpng-devel
        - libtiff-devel
        - freetype-devel
        - lcms2-devel
        - libwebp-devel
        - wireplumber-devel
        - libdbusmenu-gtk3-devel
        - playerctl-devel
        - gtk-layer-shell-devel
        - upower-devel
        - upower
        - libtool
        - libtool-ltdl
        - libtool-ltdl-devel
        - tinyxml2
        - gtkmm2.4-devel
        - gtkmm3.0-devel
        - gtkmm4.0-devel
        - cairomm
        
        # Cursors and Themes
        - bibata-cursor-themes
        - papirus-icon-theme
        
        # VPN
        - mullvad-vpn
        - globalprotect-openconnect
        - openvpn
        - NetworkManager-openvpn
        - NetworkManager-openconnect
        
        # Core Utils (most already in base)
        - coreutils
        - fuzzel
        - meson
        - typescript
        - gjs
        - jq
        - atuin
        - bash-preexec
        - fzf
        - dialog
        
        # Hyprland Ecosystem
        - hyprpaper
        - hyprpicker
        - hyprshot
        - pyprland
        - hyprcursor
        - xdg-desktop-portal-hyprland
        - waypaper
        - waypipe
        
        # Other Window Managers
        - niri
        
        # Wayland Tools
        - grim
        - slurp
        - wlr-randr
        - wlsunset
        - brightnessctl
        - swappy
        - swww
        - rofi-wayland
        - dunst
        - imv
        
        # Audio/Video
        - pavucontrol  # REMOVED DUPLICATE
        - pulseaudio-utils
        - pipewire
        - wireplumber
        - pamixer
        - playerctl  # REMOVED DUPLICATE
        
        # Bluetooth
        - bluez
        - bluez-tools
        - blueman
        - bolt
        
        # Authentication
        - fprintd-pam
        - gnome-keyring-pam
        - gnome-keyring  # REMOVED DUPLICATE
        - lxqt-policykit
        - polkit
        - pinentry-gnome3
        
        # Desktop Portals & X/Wayland
        - xorg-x11-server-Xwayland  # REMOVED DUPLICATE
        - xdg-user-dirs
        - xdg-desktop-portal-gtk  # REMOVED DUPLICATE
        - xdg-desktop-portal-wlr
        
        # D-Bus
        - dbus-tools
        - dbus-daemon
        
        # Clipboard
        - wl-clipboard
        
        # Qt Wayland
        - qt5-qtwayland
        - qt6-qtwayland
        
        # Vulkan
        - vulkan-validation-layers
        - vulkan-tools
        
        # GNOME/GTK
        - nautilus
        - gnome-disk-utility
        - google-noto-emoji-fonts
        - gnome-shell-extension-pop-shell
        - network-manager-applet
        - plymouth-system-theme
        - system-config-printer
        - libnotify
        
        # File Managers & Tools
        - thunar
        - thunar-archive-plugin
        - thunar-volman
        - xarchiver
        
        # Other Tools
        - fwupd
        - jmtpfs
        - flameshot
        - hunspell-en
        - hunspell-en-US
        - python3-pip
        - cargo
        
        # AGS (might be problematic)
        - aylurs-gtk-shell
        
        # POTENTIALLY PROBLEMATIC - Comment out if build fails
        - power-profiles-daemon  # conflicts with tuned-ppd
        - zen-twilight  # From zen-browser COPR - might not be available
        
    remove:
      packages:
        - tuned-ppd  # Conflicts with power-profiles-daemon

  - type: brew
    auto-update: true
    update-interval: '6h'
    update-wait-after-boot: '10min'
    auto-upgrade: true
    upgrade-interval: '8h'
    upgrade-wait-after-boot: '30min'
    nofile-limits: false
    brew-analytics: true

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (system-wide)"
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.valvesoftware.Steam
          - com.mattjakeman.ExtensionManager
          - md.obsidian.Obsidian
          - net.ankiweb.Anki
          - page.kramo.Cartridges
          - com.usebottles.bottles
          - com.vysp3r.ProtonPlus
          - net.davidotek.pupgui2
          - net.codelogistics.webapps
          - com.quexten.Goldwarden
          - com.bitwarden.desktop
          - org.telegram.desktop
          - com.slack.Slack
          - org.gnome.baobab
          - net.nokyan.Resources
          - com.github.tchx84.Flatseal
          - org.kde.okular
          - com.discordapp.Discord
          - io.gitlab.liferooter.TextPieces
          - io.github.flattool.Warehouse
          - org.DolphinEmu.dolphin-emu
          - com.jeffser.Alpaca
          - im.riot.Riot
          - com.stremio.Stremio
          - org.gnome.Fractal
          - com.ticktick.TickTick
          - org.libreoffice.LibreOffice
          - com.wps.Office
          - com.gopeed.Gopeed
          - org.qbittorrent.qBittorrent
          - org.chromium.Chromium
          - com.github.wwmm.easyeffects
          - com.github.rafostar.Clapper
      - scope: user
        repo:
          name: flathub-user
          title: "Flathub (User)"
        install: []

  - type: script
    scripts:
      - getbeeper.sh
      - getsimplex.sh
      - git.sh
      - enablepop.sh
      - post-install.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - Inconsolata
      google-fonts:
        - Roboto

  - type: bling
    install:
      - 1password
      - dconf-update-service

  - type: chezmoi
    repository: "https://github.com/AsirShahid/dotfiles"
    all-users: true
    file-conflict-policy: "skip"

  - type: gschema-overrides
    include:
      - zz1-myoverride.gschema.override

  - type: gnome-extensions
    install:
      - Night Theme Switcher
      - Blur my Shell
      - Bluetooth Battery Meter
      - Caffeine
      - 779  # Clipboard Indicator

  - type: systemd
    system:
      enabled:
        - power-profiles-daemon.service
      disabled: []
      masked: []
      unmasked: []
    user:
      enabled: []
      disabled: []
      masked: []
      unmasked: []

  - type: signing
