# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: myos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: dnf
    repos:
      copr:
        - atim/starship
        - solopasha/hyprland
        - ublue-os/staging
        - kylegospo/bazzite-multilib
        - kylegospo/bazzite
        - peterwu/rendezvous
        - yuezk/globalprotect-openconnect
        - yalter/niri
        - ryanabx/cosmic-epoch
        - wiiznokes/cosmic-applets-unofficial
        - sneexy/zen-browser
      files:
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
#      - https://repo.protonvpn.com/fedora/protonvpn-stable.repo
    install:
      packages:
        - starship
        - helix
        - kitty
        - alacritty
        - ptyxis
        - emacs
        - timeshift
        - gnome-shell-extension-pop-shell
        - gnome-boxes
        - kdeconnectd
        - antimicrox
        - cliphist
        - openssl-devel
        - zathura
        - zathura-pdf-mupdf
        - zathura-ps
        - zathura-djvu
        - libgda
        - libgda-sqlite
        - zlib-devel
        - libjpeg-turbo-devel
        - python3-devel
        - libpng-devel
        - libtiff-devel
        - freetype-devel
        - lcms2-devel
        - libwebp-devel
        - wireplumber-devel
        - libdbusmenu-gtk3-devel
        - playerctl-devel
        - gtk-layer-shell-devel
        - upower-devel
        - upower
        - bibata-cursor-themes
        - mullvad-vpn
        - coreutils
        - cliphist
        - fuzzel
        - gojq
        - meson
        - typescript
        - gjs
        - libtool
        - libtool-ltdl
        - libtool-ltdl-devel
        - power-profiles-daemon
        - tinyxml2
        - gtkmm2.4-devel
        - gtkmm3.0-devel
        - gtkmm4.0-devel
        - gtksourceviewmm
        - cairomm
        - hyprpaper
        - hyprpicker
        - hyprshot
        - pyprland
        - hyprcursor
        - xdg-desktop-portal-hyprland
        - waypaper
        - jq
        - waypipe
        - sway
        - waybar-git
        - grim
        - grimshot
        - swaylock-effects
        - pavucontrol
        - pulseaudio-utils
        - libnotify
        - pipewire
        - wireplumber
        - pamixer
        - blueman
        - bolt
        - fprintd-pam
        - gnome-keyring-pam
        - lxqt-policykit
        - nautilus
        - pinentry-gnome3
        - plymouth-system-theme
        - system-config-printer
        - aylurs-gtk-shell
        - cargo
        - fzf
        - swappy
        - swww
        - rofi-wayland
        - xorg-x11-server-Xwayland
        - polkit
        - lxpolkit
        - xdg-user-dirs
        - dbus-tools
        - dbus-daemon
        - wl-clipboard
        - gnome-keyring
        - pavucontrol
        - playerctl
        - qt5-qtwayland
        - qt6-qtwayland
        - vulkan-validation-layers
        - vulkan-tools
        - google-noto-emoji-fonts
        - gnome-disk-utility
        - xdg-desktop-portal-gtk
        - network-manager-applet
        - NetworkManager-openvpn
        - NetworkManager-openconnect
        - bluez
        - bluez-tools
        - blueman
        - thunar
        - thunar-archive-plugin
        - thunar-volman
        - xarchiver
        - imv
        - slurp
        - grim
        - wlr-randr
        - wlsunset
        - brightnessctl
        - swayidle
        - kanshi
        - foot
        - dunst
        - fontawesome-fonts-all
        - gnome-themes-extra
        - gnome-icon-theme
        - paper-icon-theme
        - breeze-icon-theme
        - papirus-icon-theme
        - river
        - xdg-desktop-portal-wlr
        - xdg-desktop-portal-gtk
        - fwupd
        - jmtpfs
        - globalprotect-openconnect
        - awesome
        - xorg-x11-server-Xorg
        - flameshot
        - niri
        - hunspell-en
        - hunspell-en-US
        - gtk-murrine-engine
        - openvpn
        - dialog
        - python3-pip
        - i3
        - zen-browser
        - zen-twilight
    remove:
      packages:
        - tuned-ppd

  - type: brew
    auto-update: true
    update-interval: '6h'
    update-wait-after-boot: '10min'
    auto-upgrade: true
    upgrade-interval: '8h'
    upgrade-wait-after-boot: '30min'
    nofile-limits: false
    brew-analytics: true

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (system-wide)"
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.valvesoftware.Steam
          - com.mattjakeman.ExtensionManager
          - md.obsidian.Obsidian
          - net.ankiweb.Anki
          - page.kramo.Cartridges
          - com.usebottles.bottles
          - com.vysp3r.ProtonPlus
          - net.davidotek.pupgui2
          - net.codelogistics.webapps
          - com.quexten.Goldwarden
          - com.bitwarden.desktop
          - org.telegram.desktop
          - com.slack.Slack
          - org.gnome.baobab
          - net.nokyan.Resources
          - com.github.tchx84.Flatseal
          - org.kde.okular
          - com.discordapp.Discord
          - io.gitlab.liferooter.TextPieces
          - io.github.flattool.Warehouse
          - org.DolphinEmu.dolphin-emu
          - com.jeffser.Alpaca
          - im.riot.Riot
          - com.stremio.Stremio
          - org.gnome.Fractal
          - com.ticktick.TickTick
          - org.libreoffice.LibreOffice
          - com.wps.Office
          - com.gopeed.Gopeed
          - org.qbittorrent.qBittorrent
          - org.chromium.Chromium
          - com.github.wwmm.easyeffects
          - com.github.rafostar.Clapper
      - scope: user
        repo:
          name: flathub-user
          title: "Flathub (User)"
        install: []

  - type: script
    scripts:
      - getbeeper.sh
      - getsimplex.sh
      - git.sh
      - enablepop.sh
      - post-install.sh
#      - block-ads.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - Meslo
        - Inconsolata
        - Noto
      google-fonts:
        - Roboto
        - Open Sans

  - type: bling
    install:
      - 1password
      - dconf-update-service

  - type: chezmoi
    # Installs chezmoi to /usr/bin/chezmoi from latest Github release
    # () Git repository to initialize
    repository: "https://github.com/AsirShahid/dotfiles" # Required - Default: n/a  - Expects type: string
    # Enable the modules services globally for all users
    all-users: true # Optional - Default: true - Expects type: boolean
    # Policy for handling file that has changed on disk compared to your repo. Accepts "skip" or "replace"
    file-conflict-policy: "skip" # Optional - Default: "skip" - Expects type: string

#   - type: akmods
#     base: main # if not specified, classic "main" base is used by default
#     install:
#       - framework-laptop
#       - ryzen-smu
#       - zenergy
  - type: gschema-overrides
    include:
      - zz1-myoverride.gschema.override # test & compile the override file included in config/gschema-overrides/zz1-myoverride.gschema.override     #- gcadapter_oc

  - type: gnome-extensions
    install:
      - Night Theme Switcher
      - Blur my Shell # Notice how extension is named "Blur my Shell" & not "Blur My Shell"?
                          # Name is case-sensitive, so check if extension name is typed correctly
      - Bluetooth Battery Meter
      #- Pano - Clipboard Manager
      - Caffeine
      #- PaperWM
      # Clipboard Indicator
      - 779
      #- 4245
      #- "Weather O'Clock"
      #- Pop Shell
    #uninstall:
      #- GSConnect # Uninstall step here should be used only for the extensions
                      # which are not installed through OS package manager in the base image,
                      # like extensions installed from gnome-extensions module

  - type: systemd
    system:
      enabled:
        #- nix-daemon.service
        - power-profiles-daemon.service
        #- coolercontrold.service
        #- example.service # Enabled (runs on system boot)
      disabled: []
        #- example.target # Disabled (does not run on system boot, unless other unit strictly requires it)
      masked: []
        #- example.service # Masked (does not run on system boot, under any circumstances)
      unmasked: []
        #- example.service # Unmasked (runs on system boot, even if previously masked)
    user:
      enabled: []
        #- example.timer # Enabled (runs for the user)
      disabled: []
        #- example.service # Disabled (does not run for the user, unless other unit strictly requires it)
      masked: []
        #- example.service # Masked (does not run for the user, under any circumstances)
      unmasked: []
        #- example.service # Unmasked (runs for the user, even if previously masked)

  - type: signing
